type = "card"
title = "专利&软著"
description = "发明专利和软件著作权。"

[[items]]
title = "一种海冰海水分类方法、系统、存储介质及电子设备"
subtitle = "第二作者"
date = "2023"
content = "发明专利, CN202310978838.7(已授权)"

[[items]]
title = "密文图像检索方法、装置、终端设备及存储介质"
subtitle = "第二作者"
date = "2021"
content = "发明专利, CN202110061193.1(已授权)"

[[items]]
title = "基于机器学习分类的海面风速反演方法、系统及电子设备"
subtitle = "第二作者"
date = "2023"
content = "发明专利, CN202310978258.8(实质审查)"
